version: 0.0
os: linux
files:
    - source: /
      destination: /var/www/wordpress/

hooks:
  BeforeInstall:
    - location: scripts/remove_package.sh
      runas: root
      timeout: 300

  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
